name: example
description: "A new Flutter project."
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sheetify:
    path: ../
  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  custom_lint: ^0.8.0
  sheetify_lint: ^1.0.0

flutter:
  uses-material-design: true